config/routes.rb
Rails.application.routes.draw do
  resources :problemas
  get 'home/index'

  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      get "/" => "users/sessions#new"
      get '/signout' => 'users/sessions#destroy', as: :signout
    end
  end

  root 'home#index'

  get '/get_points' => 'problemas#index'
end

app/models/problema.rb
class Problema < ActiveRecord::Base
  belongs_to :user

  mount_uploader :imagem, ProblemasUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# encoding: utf-8

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/home_controller.rb
#encoding: utf-8

class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.all
    @problemas = Problema.all.order('created_at desc')
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end
end

app/controllers/problemas_controller.rb
require 'carrierwave/orm/activerecord'

class ProblemasController < ApplicationController
  before_action :set_problema, only: [:show, :edit, :update, :destroy]

  # GET /problemas
  # GET /problemas.json
  def index
    @problemas = Problema.all
  end

  # GET /problemas/1
  # GET /problemas/1.json
  def show
  end

  # GET /problemas/new
  def new
    @problema = Problema.new
  end

  # GET /problemas/1/edit
  def edit
  end

  # POST /problemas
  # POST /problemas.json
  def create
    @problema = Problema.new(problema_params)
    puts params[:imagem]
    @problema.user_id = current_user.id

    respond_to do |format|
      if @problema.save
        format.html { redirect_to home_index_path, notice: 'Problema foi criado com sucesso!' }
        format.json { render :show, status: :created, location: @problema }
      else
        format.html { render :new }
        format.json { render json: @problema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problemas/1
  # PATCH/PUT /problemas/1.json
  def update
    respond_to do |format|
      if @problema.update(problema_params)
        format.html { redirect_to @problema, notice: 'Problema was successfully updated.' }
        format.json { render :show, status: :ok, location: @problema }
      else
        format.html { render :edit }
        format.json { render json: @problema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problemas/1
  # DELETE /problemas/1.json
  def destroy
    @problema.destroy
    respond_to do |format|
      format.html { redirect_to problemas_url, notice: 'Problema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problema
      @problema = Problema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problema_params
      params.require(:problema).permit(:titulo, :descricao, :classificacao, :endereco, :imagem, :lat, :long, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/problemas_helper.rb
module ProblemasHelper
end

app/views/home/index.html.erb
<%# encoding: utf-8 %>
<!-- Content -->
  <%= render partial: 'layouts/part_one' %>
</div>

app/views/layouts/_content.erb
<div id="mapView">
  <div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Carregando mapa...</div>
</div>
<div id="content">
  <div class="filter">
    <h1 class="osLight">Filtrar</h1>
    <a href="#" class="handleFilter"><span class="icon-equalizer"></span></a>
    <div class="clearfix"></div>
    <form class="filterForm" style="display: none;">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 formItem">
          <div class="formField">
            <label>Property Type</label>
            <a href="#" data-toggle="dropdown" class="btn btn-gray dropdown-btn dropdown-toggle propTypeSelect">
              <span class="dropdown-label">All</span>
              <span class="fa fa-angle-down dsArrow"></span>
            </a>
            <ul class="dropdown-menu dropdown-select full" role="menu">
              <li class="active"><input type="radio" name="pType" checked="checked"><a href="#">All</a></li>
              <li><input type="radio" name="pType"><a href="#">Rent</a></li>
              <li><input type="radio" name="pType"><a href="#">Sale</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 formItem">
          <div class="formField">
            <label>Price Range</label>
            <div class="slider priceSlider">
              <div class="sliderTooltip">
                <div class="stArrow"></div>
                <div class="stLabel"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 formItem">
          <div class="formField">
            <label>Area Range</label>
            <div class="slider areaSlider">
              <div class="sliderTooltip">
                <div class="stArrow"></div>
                <div class="stLabel"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 formItem">
          <div class="formField">
            <label>Bedrooms</label>
            <div class="volume">
              <a href="#" class="btn btn-gray btn-round-left"><span class="fa fa-angle-left"></span></a>
              <input type="text" class="form-control" readonly="readonly" value="1">
              <a href="#" class="btn btn-gray btn-round-right"><span class="fa fa-angle-right"></span></a>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 formItem">
          <div class="formField">
            <label>Bathrooms</label>
            <div class="volume">
              <a href="#" class="btn btn-gray btn-round-left"><span class="fa fa-angle-left"></span></a>
              <input type="text" class="form-control" readonly="readonly" value="1">
              <a href="#" class="btn btn-gray btn-round-right"><span class="fa fa-angle-right"></span></a>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
  <div class="resultsList">
    <div class="row">
      <div class="contain">
        <%= render 'problemas/partials/show' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_part_one.erb
<div id="wrapper">
  <%= render 'layouts/content' %>
</div>

app/views/layouts/application.html.erb
<%# encoding: utf-8 %>
<!DOCTYPE html>
<html>
<head>
  <title>Me Incomoda</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Católica SC">
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body  class="notransition">
<% if signed_in?%>
  <div class="flash">
  <% if alert %>
      <br><br><br>
      <div class="alert alert-danger" role="alert" style="padding: 15px 15px 15px 86px; margin-bottom: -59px; margin-top: 50px;"><%= alert %>
        <a href="#" data-dismiss="alert" class="close">x</a>
      </div>
  <% end %>
  <% if notice %>
      <div class="alert alert-success" role="alert" style="padding: 15px 15px 15px 86px; margin-bottom: -59px; margin-top: 50px;"><%= notice %>
        <a href="#" data-dismiss="alert" class="close">x</a>
      </div>
  <% end %>
  </div>
<% end %>

<% if signed_in?%>
<div class="notransition">
  <div id="header">
    <div class="logo">
      <%= link_to content_tag(:span, '', class: 'fa fa-home marker' ) + content_tag(:span, 'Início', class: 'logoText' ), '/', method: 'get' %>
    </div>
    <a href="#" class="navHandler"><span class="fa fa-bars"></span></a>
    <div class="search">
      <span class="searchIcon icon-magnifier"></span>
      <input type="text" placeholder="Procurar por problemas...">
    </div>
    <div class="headerUserWraper">
      <a href="#" class="userHandler dropdown-toggle" data-toggle="dropdown"><span class="icon-user"></span><span class="counter">5</span></a>
      <a href="#" class="headerUser dropdown-toggle" data-toggle="dropdown">

        <%= image_tag 'avatar-1.png', class: 'avatar headerAvatar pull-left', alt: 'avatar' %>
        <div class="userTop pull-left">
          <span class="headerUserName"><%= current_user.name %></span><span class="fa fa-angle-down"></span>
        </div>
        <div class="clearfix"></div>
      </a>
      <div class="dropdown-menu pull-right userMenu" role="menu">
        <div class="mobAvatar">
          <%= image_tag 'avatar-1.png', class: 'avatar mobAvatarImg', alt: 'avatar' %>
          <div class="mobAvatarName"><%= current_user.name %></div>
        </div>
        <ul>
          <li><a href="#"><span class="icon-settings"></span>Configurações</a></li>
          <li><a href="profile.html"><span class="icon-user"></span>Perfil</a></li>
          <li><a href="#"><span class="icon-bell"></span>Notificações <span class="badge pull-right bg-red">5</span></a></li>
          <li class="divider"></li>
          <li>
            <%= link_to content_tag(:span, '', class: 'icon-power' ) + "Sair", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>
    <div class="headerNotifyWraper">
      <a href="#" class="headerNotify dropdown-toggle" data-toggle="dropdown">
        <span class="notifyIcon icon-bell"></span>
        <span class="counter">5</span>
      </a>
      <div class="dropdown-menu pull-right notifyMenu" role="menu">
        <div class="notifyHeader">
          <span>Notificações</span>
          <a href="#" class="notifySettings icon-settings"></a>
          <div class="clearfix"></div>
        </div>
        <ul class="notifyList">
          <li>
            <a href="#">
              <%= image_tag 'avatar-1.png', class: 'avatar pull-left', alt: 'avatar' %>
              <div class="pulse border-grey"></div>
              <div class="notify pull-left">
                <div class="notifyName">Sed ut perspiciatis unde</div>
                <div class="notifyTime">5 minutes ago</div>
              </div>
              <div class="clearfix"></div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="notifyRound notifyRound-red fa fa-envelope-o"></div>
              <div class="pulse border-red"></div>
              <div class="notify pull-left">
                <div class="notifyName">Lorem Ipsum is simply dummy text</div>
                <div class="notifyTime">20 minutes ago</div>
              </div>
              <div class="clearfix"></div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="notifyRound notifyRound-yellow fa fa-heart-o"></div>
              <div class="pulse border-yellow"></div>
              <div class="notify pull-left">
                <div class="notifyName">It is a long established fact</div>
                <div class="notifyTime">2 hours ago</div>
              </div>
              <div class="clearfix"></div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="notifyRound notifyRound-magenta fa fa-paper-plane-o"></div>
              <div class="pulse border-magenta"></div>
              <div class="notify pull-left">
                <div class="notifyName">There are many variations</div>
                <div class="notifyTime">1 day ago</div>
              </div>
              <div class="clearfix"></div>
            </a>
          </li>
        </ul>
        <a href="#" class="notifyAll">See All</a>
      </div>
    </div>
    <a href="#" class="mapHandler"><span class="icon-map"></span></a>
    <div class="clearfix"></div>
  </div>

  <!-- Left Side Navigation -->

  <div id="leftSide">
    <nav class="leftNav scrollable">
      <ul>
        <li>
          <%= link_to content_tag(:span, '', class: 'navIcon icon-plus' ) + content_tag(:span, 'Novo', class: 'navLabel' ), new_problema_path, method: 'get' %>
        </li>
        <li><a href="index.html"><span class="navIcon icon-compass"></span><span class="navLabel">Meus</span></a></li>
        <li><a href="index.html"><span class="navIcon icon-clock"></span><span class="navLabel">Recentes</span></a></li>
        <li><a href="index.html"><span class="navIcon icon-heart"></span><span class="navLabel">Favoritos</span></a></li>
        <li class="hasSub">
          <a href="#"><span class="navIcon icon-pointer"></span><span class="navLabel">Outros</span><span class="fa fa-angle-left arrowRight"></span></a>
          <ul class="colors">
            <li><a href="index.html">Mais votados <span class="fa icon-right"></span></a></li>
            <li><a href="index.html">Mais proximos <span class="fa icon-right"></span></a></li>
            <li><a href="index.html">Mais vistos <span class="fa icon-right"></span></a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
  <div class="closeLeftSide" style="display: none;"></div>
  <%= yield %>
</div>
</body>
<% else %>
  <body  class="notransition">
    <%= yield %>
  </body>
<% end %>
<!--<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDof2nyTF4EdM7UzYT1ISsZa2bc5VUms6s"></script>-->
<!--<script src="http://maps.googleapis.com/maps/api/js?sensor=true&amp;libraries=geometry&amp;libraries=places" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp" type="text/javascript"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDof2nyTF4EdM7UzYT1ISsZa2bc5VUms6s&callback=initMap"></script>-->
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&amp;libraries=geometry&amp;libraries=places" type="text/javascript"></script>
<%= javascript_include_tag 'infobox' %>
<%= javascript_include_tag 'app' %>
</html>

app/views/problemas/_form.html.erb
<%= form_for(@problema) do |f| %>
  <% if @problema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problema.errors.count, "error") %> prohibited this problema from being saved:</h2>

      <ul>
      <% @problema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div id="wrapper">
      <div id="mapView" class="mob-min"><div class="mapPlaceholder"><span class="fa fa-spin fa-spinner"></span> Carregando mapa...</div></div>
      <div id="content" class="mob-max">
        <div class="rightContainer">
          <h1>Insira um novo problema</h1>
            <div class="form-group">
              <label>Buscar Endereço<br></label>
              <%= f.text_field :endereco, class: 'form-control endereco', placeholder: "Entre com a localização", :autocomplete=>"on" %>
              <p class="help-block">Você pode arrastar o marcador para a posição desejada</p>
            </div>
            <div class="form-group">
                <label>Título</label><br>
                <%= f.text_field :titulo, class: 'form-control', required: 'True' %>
            </div>
            <div class="form-group">
              <label>Descrição</label><br>
              <%= f.text_area :descricao, rows: '4', class: 'form-control', required: 'True' %>
            </div>
            <div class="form-group">
              <button type="button" class="btn btn-gray problema_classificacao">1</button>
              <button type="button" class="btn btn-gray problema_classificacao">2</button>
              <button type="button" class="btn btn-gray problema_classificacao">3</button>
              <button type="button" class="btn btn-gray problema_classificacao">4</button>
              <button type="button" class="btn btn-gray problema_classificacao">5</button>
              <p class="help-block">Classificação <span class="value-classificacao">5</span></p>
              <%= f.hidden_field :classificacao, value: '5' %>
            </div>
            <div class="form-group">
              <label>Latitude/Longitude: <span id="latitude" class="label label-default latitude"></span> <span id="longitude" class="label label-default longitude"></span>
                  <%= f.hidden_field :lat, class: 'lat'%>
                  <%= f.hidden_field :long, class: 'long'%>
              </label>
            </div>
            <div class="form-group">
              <label>Imagem</label>
              <%= f.file_field :imagem, class: 'file file_field', 'data-show-upload' => false, 'data-show-caption' => false, 'data-show-remove'=> true, :accept=>"image/jpeg,image/png", 'data-browse-class'=>"btn btn-o btn-default", 'data-browse-label'=>"Procurar imagem", required: 'True', accept: 'image/.jpeg, .jpg, .gif, .png' %>
              <p class="help-block">Você pode selecionar uma imagem por vez</p>
            </div>
            <div class="form-group">
              <%= f.submit "Adicionar", class: "btn btn-green btn-lg" %>
            </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
<% end %>

app/views/problemas/edit.html.erb
<h1>Editing Problema</h1>

<%= render 'form' %>

<%= link_to 'Show', @problema %> |
<%= link_to 'Back', problemas_path %>

app/views/problemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Problemas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Classificacao</th>
      <th>Endereco</th>
      <th>Imagem</th>
      <th>Lat</th>
      <th>Long</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @problemas.each do |problema| %>
      <tr>
        <td><%= problema.titulo %></td>
        <td><%= problema.descricao %></td>
        <td><%= problema.classificacao %></td>
        <td><%= problema.endereco %></td>
        <td><%= problema.imagem %></td>
        <td><%= problema.lat %></td>
        <td><%= problema.long %></td>
        <td><%= problema.user %></td>
        <td><%= link_to 'Show', problema %></td>
        <td><%= link_to 'Edit', edit_problema_path(problema) %></td>
        <td><%= link_to 'Destroy', problema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problema', new_problema_path %>

app/views/problemas/new.html.erb
<%= render 'form' %>

app/views/problemas/partials/_show.html.erb
<% @problemas.each do |problema| %>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <a href="single.html" class="card">
        <div class="figure">
          <%= image_tag problema.imagem %>
        </div>
        <h2><%= problema.titulo %></h2>
        <div class="cardAddress"><span class="icon-pointer"></span> <%= problema.endereco %></div>
        <div class="cardRating" data-id="<%= problema.id %>">
          <script>adicionaEstrelas(<%= problema.classificacao %>, <%= problema.id %>)</script>
        </div>
        <ul class="cardFeat"></ul>
        <div class="clearfix"></div>
      </a>
    </div>
<% end %>
  <!--<ul class="pagination">
    <li class="disabled"><a href="#"><span class="fa fa-angle-left"></span></a></li>
    <li class="active"><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#"><span class="fa fa-angle-right"></span></a></li>
  </ul>
    -->

app/views/problemas/partials/edit.js.erb
alert('teste');
console.dir('teste');
<% puts 'teste' %>

app/views/problemas/partials/index.js.erb
alert('teste');
console.dir('teste');
<% puts 'teste' %>

app/views/problemas/partials/mostrar.js.erb
<% @problemas.each do |problema| %>
  $(".contain").append("<%= escape_javascript render 'problemas/partials/show', :problema => problema %>");
<% end %>

app/views/problemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @problema.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @problema.descricao %>
</p>

<p>
  <strong>Classificacao:</strong>
  <%= @problema.classificacao %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @problema.endereco %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @problema.imagem %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @problema.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @problema.long %>
</p>

<p>
  <strong>User:</strong>
  <%= @problema.user %>
</p>

<%= link_to 'Edit', edit_problema_path(@problema) %> |
<%= link_to 'Back', problemas_path %>